apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-login-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-login-app
  template:
    metadata:
      labels:
        app: java-login-app
    spec:
      containers:
      - name: java-login-app
        image: digdigdigdig/java-login-app:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: java-login-app-service
spec:
  selector:
    app: java-login-app
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer
